# Generated by Django 5.2.9 on 2025-12-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cartao', models.CharField(max_length=200, verbose_name='Nome do Cartão')),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Limite')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cartão Virtual',
                'verbose_name_plural': 'Cartões Virtuais',
                'ordering': ['-criado_em'],
            },
        ),
    ]
